name: Update GFG Stats

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-gfg-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch GFG Stats
        run: |
          mkdir -p profile

          curl -L \
            "https://gfg-stats.tashif.codes/codewithsuraj1/stats/svg?theme=dark" \
            -o profile/gfg-stats.svg

      - name: Commit updated GFG stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/gfg-stats.svg

          git diff --cached --quiet || git commit -m "Update GFG stats"

          git push
